spring.application.name=qkart
spring.datasource.url=jdbc:postgresql://localhost:5432/qkart_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret=ThisIsAVeryStrongSecretKeyForQKartJwtAuthentication12345
jwt.expiration=86400000